baseURL = 'https://st0rmESP.github.io/'
languageCode = 'es'
title = 'st0rmESP | Cyber Security Writeups'
theme = 'PaperMod' # O el que elijas

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai" # Estilo de colores tipo hacker
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
