baseURL = 'https://st0rmESP.github.io/'
languageCode = 'es'
title = 'st0rmESP | Cyber Security Writeups'
theme = 'PaperMod' # O el que elijas

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai" # Estilo de colores tipo hacker
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "htb"
    name = "HackTheBox"
    url = "/categories/hackthebox/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Etiquetas"
    url = "/tags/"
    weight = 30

[params]
    env = "production"
    title = "st0rmESP"
    description = "Writeups de Ciberseguridad | CTF Player | Cryptography"
    defaultTheme = "dark"
    ShowCodeCopyButtons = true
    
    # --- PERFIL DE LA P√ÅGINA PRINCIPAL ---
    [params.profileMode]
        enabled = true
        title = "st0rmESP üö©"
        subtitle = "Bienvenido a mi rinc√≥n de ciberseguridad. Aqu√≠ comparto mis writeups de **HackTheBox**, retos de **criptograf√≠a** y mis notas de aprendizaje sobre seguridad ofensiva."
        imageUrl = "https://github.com/st0rmESP.png" # Esto toma tu foto de GitHub autom√°ticamente
        imageWidth = 150
        imageHeight = 150
        imageTitle = "st0rmESP"
        
        [[params.profileMode.buttons]]
            name = "Writeups"
            url = "/posts"
        [[params.profileMode.buttons]]
            name = "Sobre m√≠"
            url = "/about"

    # --- REDES SOCIALES ---
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/st0rmESP"
    [[params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/tu_usuario"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/tu_perfil"