baseURL = 'https://st0rmESP.github.io/'
languageCode = 'es'
title = 'st0rmESP | Cyber Security Writeups'
theme = 'PaperMod' # O el que elijas

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai" # Estilo de colores tipo hacker
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "htb"
    name = "HackTheBox"
    url = "/categories/hackthebox/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Etiquetas"
    url = "/tags/"
    weight = 30

[params]
    env = "production"
    title = "st0rmESP"
    description = "Writeups de Ciberseguridad y Retos CTF"
    defaultTheme = "dark" # Forzar modo oscuro por defecto
    showCodeCopyButtons = true # Bot칩n para copiar c칩digo (clave para payloads)
    displayFullPostContent = false
    
    [params.homeInfoParams]
        Title = "Bienvenido a st0rmESP 游뛀"
        Content = "Aqu칤 encontrar치s mis resoluciones de m치quinas de Hack The Box, TryHackMe y retos de criptograf칤a."

    [params.assets]
        disableHLJS = false # Activar resaltado de sintaxis
[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai" # Estilo oscuro tipo terminal
    lineNos = true    # Mostrar n칰meros de l칤nea

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/st0rmESP"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/tu-perfil"
